# Generated by Django 4.1.7 on 2023-04-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_service_date_alter_service_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='driver',
            new_name='car',
        ),
    ]
