# Generated by Django 4.1.7 on 2023-04-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_driver_service_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-date',)},
        ),
    ]
