# Generated by Django 4.1.7 on 2023-04-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to='main_app.driver'),
        ),
    ]
